spring:
  profiles: test
  # REDIS (RedisProperties)
  redis:
    # 连接超时时间（ms）
    timeout: 10000
    # Redis数据库索引（默认为0）
    database: 4
    # Redis服务器地址
    host: 127.0.0.1
    port: 6379
    password: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0



