spring:
  profiles: test
  # REDIS (RedisProperties)
  redis:
    # 连接超时时间（ms）
    timeout: 10000
    # Redis数据库索引（默认为0）
    database: 4
    # Redis服务器地址
    host: 127.0.0.1
    port: 6379
    password: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  kafka:
    bootstrap-servers: 172.21.2.77:9092
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: test1
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    listener:
      concurrency: 6


